### ISSUE TITLE
Removes ISG15 from host proteins

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#132]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Removes ISG15 from host proteins

## Synonyms
None

## Textual definition
Interferon-stimulated gene 15 (ISG15; it has a molecular mass of ~15 kDa) is a small, ubiquitin-like protein that can be added to host proteins (ISGylation) upon infection by an intracellular parasite (https://en.wikipedia.org/wiki/ISG15). It serves as a signal of viral presence. Removal of these  dampens inflammation and antiviral signaling. SARS-CoV2 and Crimean Congo Hemorrhagic fever both have proteases that act as deubiquitinases but also serve to remove ISG15 units from host proteins. But most deubiquitinases do not also act as de-ISG15ases (I just made up the latter term.)

## Suggested parent term
I am tempted to suggest putting this  under "modulates ubiquitin dynamics", but this isn't really ubiquitin so that doesn't make sense. I do not foresee that a parasite protein will be discovered that actually *adds* ISG15 to host proteins, so I don't think a "modulates ISG15 dynamics" term is needed. Perhaps it would be best to use the parent term for "modulates ubiquitin dynamics"?

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold I'm thinking immune evasion and subversioon...

**Comment by genegodbold** [comment]
@jproesch Yes, it will certainly be doing that--so as a parent term, then?

**Comment by jacakrj1** [comment]
Added in terms related to ISGylation under 'mediates immune evasion and subversion'.
