### ISSUE TITLE
Chaperone for secretion of bacterial effector

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#134]
Actually, forget about this one.

**Comment by jproesch** [comment]
@genegodbold Can you provide more context for this?  Trying to figure out where something like this would fit. This is involved in effector secretion?  If so, may not really be acting on the host...

**Comment by genegodbold** [comment]
@jproesch Yes, these are things that can help both effectors and needle/secretion system components get from the inside of the bacterial cell to the outside or into the right position in the secretion system. They're pretty minor things, but secretion systems couldn't work without them.

**Comment by jacakrj1** [comment]
This should be covered by the new term that was added under issue #194 .
