### ISSUE TITLE
Add definitions for PATHGO_0000200-PATHGO_0000204 and PATHGO_0000238-PATHGO_0000241

### ISSUE THREAD

**Issue by jproesch** [jhuapl-bio/pathogenesis-gene-ontology#142]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
(e.g., Asplenia)

## Synonyms
(e.g., Absent spleen)

## Textual definition
the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term
Please look at the hierarchy in the Protege browser, and provide the PathGO id or rdfs:label of the suggested parent term.

## Attribution
If you would like a nanoattribution, please indicate your ORCID id.

**Comment by jproesch** [comment]
@kzudock @aernlund These terms all need definitions if either of you has time to pick this up it would be greatly appreciated!

**Comment by kzudock** [comment]
I addressed these in pull request #147.
