### ISSUE TITLE
determinant of effector secretion term definitions and alignment of terms to mechanism branch

### ISSUE THREAD

**Issue by jproesch** [jhuapl-bio/pathogenesis-gene-ontology#146]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
(e.g., Asplenia)

## Synonyms
(e.g., Absent spleen)

## Textual definition
the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term
Please look at the hierarchy in the Protege browser, and provide the PathGO id or rdfs:label of the suggested parent term.

## Attribution
If you would like a nanoattribution, please indicate your ORCID id.

**Comment by jacakrj1** [comment]
Determinant branch was removed, so this issue no longer applies.

**Comment by jacakrj1** [comment]
Looked over the state of the ontology in November of last year (when this comment was added) and there wasn't any information on the determinant side that wasn't copied over to the mechanism side.
