### ISSUE TITLE
Nutrient availability and uptake factor and alignment to mechanism branch

### ISSUE THREAD

**Issue by aernlund** [jhuapl-bio/pathogenesis-gene-ontology#149]
Mediates nutrient availability or uptake (PATHGO:0000113) on the mechanism branch has 5 children terms that are not represented as children terms for nutrient availability and uptake factor (PATHGO:0000067) on the determinant branch.

**Comment by jacakrj1** [comment]
Determinant branch was removed, so this issue no longer applies.
