### ISSUE TITLE
Eukaryotic initiation modulator factor duplicated in determinant branch

### ISSUE THREAD

**Issue by aernlund** [jhuapl-bio/pathogenesis-gene-ontology#150]
Eukaryotic initiation modulator factor (PATHGO:0000262) child of cellular metabolism disruption factor (PATHGO:0000179) should be removed along with children terms. This term (PATHGO:0000034) is also represented as a child term of protein synthesis modulation factor.

**Comment by jproesch** [comment]
removed Eukaryotic initiation modulator factor (PATHGO:0000262) and children
