### ISSUE TITLE
apoptosis modulator / regulation of apoptosis factor duplicate terms

### ISSUE THREAD

**Issue by aernlund** [jhuapl-bio/pathogenesis-gene-ontology#151]
On determinant branch, host cell apoptosis modulator (PATHGO:0000333) and children terms do not have definitions. Regulation of apoptosis factor (PATHGO:0000192) is a redundant term on this branch and should be considered for removal.

**Comment by jproesch** [comment]
removed (PATHGO:0000192), but see existing definitions for 333 and children
