### ISSUE TITLE
"Passive" immune evasion

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#156]
So I've documented ~80 sequences of concern with enzymatic activity of various sorts, the "goal" of which (and putting aside teleology, certainly the effect of which) seems to be to  *decrease* the recognition of a microbial associated molecular pattern (MAMP) OR something normally targeted by a host immune effector. 

So these parasite proteins are modifying parasite features that the host innate immune system normally recognizes. The enzymatic activity in question alters the feature so as to render it *less* reactive/less susceptible to recognition by (say) host pattern recognition receptors, cationic antimicrobial peptides (AMPs) or complement.

I have been calling these things examples of "passive" immune evasion to differentiate them from active things that directly affect host immune effectors. So this "class" of things acts on the *target* of the host immune detector or effector and NOT on the effector itself.

Should this be a "thing" in the ontology? I think it should be noted (somehow) that something is having this sort of effect, even though it is not directly affecting the host.

Some examples:
1. PagP of Bordetella bronchiseptica is a palmitoyl transferase responsible for the addition of a palmitoyl group to lipid A of the LPS of B. bronchiseptica. When PagP is deleted from B. bronchiseptica, the LPS lacking the palmitoylated lipid A moiety does not protect the bacteria from antibody-mediated complement killing at low concentrations of immune serum [PMID15102794].
2. AlgC of Acinetobacter baumannii is one of 50 proteins involved in the maintenance of lipid asmymetry (Mla) genetic pathway in Acinetobacter baumannii that is responsible for protecting the bacterium from the bactericidal, via complement, effects of host serum. The pathway renders the bacterium highly resistant to complement-mediated killing [PMID28855313].
3. AlmG is a peripheral membrane aminoacyl transferasae that modifies Vibrio cholerae lipopolysaccharide (LPS) to provide resistance to destruction by cationic antimicrobial peptides. In Vibrio cholerae it functions in an operon with AlmE and AlmF [PMID29101229].
4. MlaA is a VacJ-family lipoprotein that is one of 50 involved in the maintenance of lipid asymmetry (Mla) genetic pathway in Acinetobacter baumannii that is responsible for protecting the bacterium from the bactericidal, via complement, effects of host serum. The pathway renders the bacterium highly resistant to complement-mediated killing [PMID28855313].
4. Cbu0678 is essential for production of phase I LPS in C. burnetii [PMID29481553]. It codes for a D-glycero-D-manno-heptose-1-phosphate adenylyltransferase with two domains. It is predicted to make ADP-D-glycero-beta-D-mann-heptose, a sugar found in the inner core of the LPS of the bacterium [PMID14524481].  In virulent bacteria, lipid A of LPS is decorated (or capped) with an inner core of two (each) heptose and mannose residues, an outer core of mannose and heptose, then the outermost O-antigen composed of six sugar monomers including virenose. The C. burnetii O-antigen is not very antigenic and the sugars shield the bacterial LPS from host immune recognition of the inner and outer core--which are highly antigenic [PMID29481553]. 
5. Host RIG-like receptors use the presence of a 5' cap to distinguish viral RNA from host mRNA. NSP14 has guanine N7-methyltransferase activity that can produce a cap structure on viral RNA [PMID19208801]. NSP16 of SARS-CoV further modifies this cap with its 2’-O-methyl-transferase activity, allowing the virus to efficiently evade recognition by host MDA5 [PMID21085181].
6. Lic2B (and Lic2C) are involved in the production of the outer core of the lipooligosaccharide (LOS) of Haemophilus influenzae. Lic2B is a glycosyltransferase that is involved in serum resistance of H. influenzae. A strain of bacteria in which the lic2B gene is missing are unable to resist complement-mediated destruction. Lic2B is critical for optimal survival of bacteria in a mouse model of bacteremia. The carbohydrate structures allowed by Lic2B enable the bacterium to resist killing by the classical complement pathway [PMID21357723].
7. Lipid A 1-phosphatase and lipid A 4'-phosphatase are novel lipid phosphatases of Porphyromonas gingivalis that dephosphorylate lipid A of the bacterial lipopolysaccharide component of the cell wall to reduce the ability of the pattern recognition receptor TLR4 to detect the organism. Non-phosphorylated lipid A is the structural feature that allows the LPS of P. gingivalis to escape TLR4 activation [PMID19552698]. Most types of lipid A molecules are detected at picomolar levels by TLR4 that is present on macrophages and endothelial cells [PMID12045108]. TLR4 is more stimulated by E. coli penta-acylated lipid A that is phosphorylated at position 1 than it is by penta-acylated lipid A phosphorylated at position 4'. The cationic antimicrobial peptide polymyxin B is less likely to bind to the dephosphorylated, non-tetra-acylated lipid A LPS of P. gingivalis [PMID20974832]. 
8. LptA of Neisseria gonorrhoeae catalyzes the transfer of phosphoethanolamine (PEA) to the 4' phosphate group of lipid A of gonococcal lipooligosaccharide (LOS), an abundant surface constituent of the bacterium. Loss of LptA leads to a decrease in the bacteria's ability to resist killing by host complement, cationic antimicrobial peptides, and neutrophil extracellular traps [PMID25537831]. Purified LOS lacking the PEA modification on lipid A results does not provoke as strong a proinflammatory response from human enbryonic kidney cells expressing TLR4/MD2/CD14 as measured by NFkappaB activation [PMID24686069]. While in some bacteria, a less inflammatory profile would be advantageous, for N. gonnorrhoeae, a proinflammatory response that attracts neutrophils is preferred [PMID29016383].
9. MprF enzymatically modifies the charge of the outer membrane by coupling phosphatidylglycerol (PG) with L-lysine (Lys-PG). This reduces the negative charge on the membrane and thus protects it against cationic antimicrobial peptides [PMID18592144]. Bacteria in which MprF is mutated (including S. aureus, B. anthracis, L. monocytogenes, and R. tropici), such that they lack or have much reduced Lys-PG, are highly susceptible to antimicrobial peptides. Deletion of the gene encoding MprF results in "profoundly reduced virulence of several bacterial pathogens in animal models"  [PMID19915718].
10. N-acetyltransferase modifies bacterial lipidA to reduce the ability of the host to detect the bacterium [PMID22586119]. An F. novicida mutant in which the gene for LpxD1 was deleted was avirulent in a murine model of infection. Mice infected subcutaneously with up to 500,000 lethal doses (10 cfu = LD100) all survived infection and showed no signs of disease. Lipopolysaccharide isolated from bacterial mutants missing either LpxD1 or LpxD2 were not recognized by components of the host innate immune system, suggesting that lipid A molecules with long chain acyl groups have altered binding propoerties to the TLR4-CD14-MD-2 complex [PMID22586119].
11. N-deacetylation of peptidoglycan by the the product of the pgdA gene allows Listeria monocytogenes to evade several components of the innate immune system including recognition by the Toll-like receptor 2 (TLR2) and the NOD1 protein. The activity of the product of the pgdA gene renders the bacterium more resistant to the lytic activity of lysozyme [PMID25157076]. Without deacetylation, the bacterium is 100,000 times more susceptible to killing by lysozyme. L. monocytogenes expressing a nonfunctional copy of the pgdA gene are impaired for survival in macrophages as well as for survival in the intestine. They do not escape the phagosome as do wild type bacteria. L. monocytogenes expressing a nonfunctional copy of the pgdA gene produce a far greater cytokine response (IL-6 and IFNβ in macrophages compared to those expressing a functional copy [PMID17215377]. 

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold I think this is fair as a concept to represent.  However, these gene products are made by the pathogen and act on the pathogen.  That isn't necessarily a basis for exclusion, but it does mean it doesn't work under 'modulates host immune function'. Perhaps this should go in the indirect branch.  "mediates passive immune evasion" strikes me as too generic, maybe "dampens recognition by host innate immune system"?  Also not particularly satisfying...

**Comment by genegodbold** [comment]
@jproesch Let's work with your second suggestion; how about something like "modifies parasite molecule to decrease host immune recognition"?

My one concern is whether this definition is broad enough to include something like Lic2b (number 7 above) or MprF (number 10 above)? Their activity is designed to avoid complement and antimicrobial peptide activity--those obviously are NOT pattern recognition receptors but rather immune effectors. They are avoiding "detection" by those particular effectors, though.

**Comment by jproesch** [comment]
@genegodbold I think the definition can be broad enough to include avoiding complement and AMPs

**Comment by genegodbold** [comment]
@jproesch Wait, wait--I **want** to include them!

**Comment by jproesch** [comment]
@genegodbold yes, I think you can with the definition I wrote! :)
