### ISSUE TITLE
Small GTPase activating protein

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#158]
Currently the ontology has two children under the parent PATHGO_0000181 (GTPase activating protein)
1. PATHGO_0000276 Small GTPase activating protein
2. PATHGO_0000277 Heterotrimeric GTPase activating protein

I think we need a third because there are a fair number of proteins that **activate** small GTPases by **deamidation** including

- Cytotoxic necrotizing factor from E. coli
- VopC from Vibrio parahaemolyticus
- Cytotoxic necrotizing factor-gamma from Yersinia enterocolitica
- Dermonecrotic toxin of Bordetella sp.

For new term requests, please provide the following information:
## Preferred term label
Small GTPase activation via deamidation (this probably needs work)

## Synonyms
None

## Textual definition
These proteins activate host small GTPases by enzymatically removing an amine group at a conserved glutamine residue, changing it to glutamate/glutamic acid and causing the constitutive activation of the small GTPase.

## Suggested parent term
PATHGO_0000181 (GTPase activating protein)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by kzudock** [comment]
Decided this is covered by PATHGO:0000278 "stimulates small GTPase activity"

**Comment by genegodbold** [comment]
@kzudock, I think this is in the determinant branch so it is going away anyway, but there is a need to capture **how** a parasite sequence mediates the activation of host GTPases. Deamidation leads to constitutive activation of the small GTPases. This is irreversible and it would be good to know that a parasite sequence is doing this. It could also function as a GTPase activating protein (GAP) and mediate _de_activation by stimulating the natural GTPase activity of the small GTPase. Or it can act as a guanine exchange factor (GEF) and mediate **activation** by kicking out the GDP. (Since there is more GTP than GDP in a normal cell, this tends to activate the protein.) The latter two are reversible. Anyway, certain intracellular bacterial parasites can do all three of these things and it is good to specify which is occurring.

(FWIW, I studied these things in a protozoan parasite as a postdoc in the 90s.)

**Comment by kzudock** [comment]
Ah, many thanks for the explanation, Gene! Our concern with adding a term for deamination specifically is that we are not getting this granular into the chemistry with any other terms in the ontology. However, it sounds like there are a number of downstream effects that would be important to incorporate if not already covered by GO.

**Comment by genegodbold** [comment]
@kzudrock How about this term: "mediates constitutive activation of host small GTPase"
This would cover the parasite deamidases

Alternately, "mediates activation of host small GTPase"
This would cover both the deamidases and the guanine exchange factors (GEFs, which don't activate the small GTPases constitutively).

Then we need a term for "mediates deactivation of host small GTPase". This would include the GTPase activating proteins (GAPs) which sound like they activate the small GTPases but actually deactivate them since it gets rid of the GTP.

The parent term for these two would be "modulates activation of host small GTPase"

**Comment by kzudock** [comment]
Yes, I definitely like mediates constitutive activation of host small GTPase and mediates deactivation of host small GTPase. Will add! Thanks, Gene!

**Comment by genegodbold** [comment]
@kzudock Let's keep it simpler by knocking out the "constitutive" so it covers both deamidases and GEFs.

**Comment by kzudock** [comment]
Sounds good 👍
