### ISSUE TITLE
Disruption of host TRIM/TRIM-like protein signaling

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#161]
For new term requests, please provide the following information:
## Preferred term label
Disruption of host TRIM protein or TRIM-like protein signaling

## Textual definition
TRIM (Tripartite motif) and TRIM-like proteins are an important class of E3 ligases in innate immunity. They can activate or regulate innate immune signaling pathways to direct detection and restriction of pathogens. Some intracellular parasite proteins (AnkB from Legionella, PtpA from M. tuberculosis, SopA from Salmonella, SseK3 from Salmonella, NS1 from influenza virus, NSP11 from PRRSV) target TRIMs to interfere with host immune signaling.   

## Suggested parent term
PATHGO_0000165 Disrupts host cellular signaling

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
@kzudock When adding this term, please think about whether we should be also adding terms under 'disrupts cellular metabolism' like a 'modulates protein turnover' term.
