### ISSUE TITLE
Elimination or (re)placement of "PATHGO_0000094 Mitogen-activated protein kinase kinases (MAPKKs) protease"

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#162]
The parent of "PATHGO_0000094 Mitogen-activated protein kinase kinases (MAPKKs) protease" is currently "PATHGO_0000015 Cellular signaling disruption factor" but I suggest that it might be more accurate to place it under "PATHGO_0000288 Host MAPK signaling disruption factor"

For what it's worth, I only know of one MAPKK protease (anthrax lethal factor) while there are over a dozen MAPK signaling disruption factors so you could just drop this ontology entry and it would fit just fine under the latter. In retrospect of the annotation that has been done, it is an oddly specific ontology entry.

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
This term got dropped when the determinant branch was removed so issue is no longer relevant.  Agree that it was a highly specific term considering other areas of the ontology.
