### ISSUE TITLE
Secretion effectors (type I through type VII)

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#163]
I was leaning against this at first, but I figure we might as well note if certain proteins are secreted effectors of particular secretion systems. FWIW, there will be *hundreds* of these for T3SS and T4SS effectors alone.

For new term requests, please provide the following information:
## Preferred term label
Protein effector of type 1/2/3/4/5/6/7 secretion system

## Synonyms
None

## Textual definition
These are proteins that are secreted from a bacterium via a particular secretion system. Some of them are secreted into the extracellular milieu while others are injected into the host cell (or another bacterium, though we won't be documenting those).

## Suggested parent term
I am not sure where this should go. Maybe a new intermediary term should be "Effector protein of bacterial secretion system" with that the parent of the various "Effector protein of type 1/2/3/4/5/6/7 secretion system"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
We discussed this morning that 'protein secretion' by itself is not a mechanism of pathogenesis.  It's really the thing that's secreted or injected (i.e. the effector) that causes the pathogenic effect.  GO covers 'protein secretion' and the different types, so we are leaning toward excluding it.  Thoughts here @genegodbold ?  Would a liposome with nothing but a T6SS (or other type) be pathogenic to cells?

**Comment by genegodbold** [comment]
Yes, I would be fine with this formulation. I think it makes sense and I think it is consistent.

I think that chaperones that accompany a virulence protein to protect it from host destruction *and* that might potentiate the virulence factor activity should be the one part of secretion systems that might be considered separately, but if you've got that new "modulates virulence factor activity" designator, then "chaperone protein" could go under it. (And I'm guessing "transcription factor of virulence" could fit under that rubric as well.)

You should call these (very) different modulators out as children under the "modulates VF activity" term, though. I think that would be best.

**Comment by jproesch** [comment]
@genegodbold 'mediates secretion of protein effectors' <http://purl.obolibrary.org/obo/PATHGO_0000110> is currently a child to "indirect mechanism of pathogenicity".

**Comment by genegodbold** [comment]
@jproesch Could we get a "chaperones virulence factor" child under the parent term "modulates virulence factor activity". I am trying (and perhaps failing) to use "chaperone" as a verb.

It would also be nice to have something similar for venom components since there are chaperone-like proteins that serve to potentiate the survival of the venom component (in the blood and tissues of the target) AND the activity of the venom component. Should I open this as a separate issue or would you hate me if I do that? :-)
