### ISSUE TITLE
Actin stabilization factor AND Mediates actin stabilization

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#164]
I have identified some T3SS effectors from E. coli (EHEC): EspO1-1 and EspO1-2. These resemble OspE from Shigella.  EspO1-1 localizes to host cell focal adhesions and stabilizes them along with the actin cytoskeleton in EHEC infected epithelial cells. EspO1-2 localizes to the cytoplasm but additively stabilizes both focal adhesions and the actin cytoskeleton. EspO1-2 associates via its C terminal residues (61-93) with the EspM2 T3SS effector. This EspO1-2 interaction with EspM2 inhibits formation of host actin stress fibers that are induced by EspM2 [PMID23409096].  

For new term requests, please provide the following information:
## Preferred term label
Actin stabilization factor AND Mediates actin stabilization

## Synonyms
None

## Textual definition
Parasite proteins that act to stabilize filamentous actin of the host cells.

## Suggested parent term
_Actin stabilization factor_ should be a child of PATHGO_0000183 Host cell cytoskeleton modulator
_Mediates actin stabilization_ should be a child of PATHGO_0000028 Modulates cytoskeleton in host cell

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
I went ahead and created a 'mediates host actin stabilization' term, but I'm not sure the effectors you write about above really have that function.  It sounds more like those proteins stabilize the interaction between actin and focal adhesion proteins.  Maybe I'm misunderstanding their functions, though.  Either way, I suspect there are other examples of host actin stabilization that are not polymerization, rearrangement, or crosslinking based (terms we already have).  Am wondering if we should have 'stabilization' and 'destabilization' as parent terms under which the different forms/mechanisms live.

**Comment by jproesch** [comment]
@genegodbold is an actin destabilization term needed as well?  (we have stabilization and destabilization for microtubles)

**Comment by genegodbold** [comment]
@jproesch Without going on a dive into the literature OR my spreadsheet, I would say "yes". I remember learning actin dynamics in graduate school with a guy who had actually done some of the work and there are a crap-ton of permutations. I am pretty sure bugs mess with all aspects of actin from upstream signaling to modifications of the actin protein itself (some Clostridial toxins do this).
