### ISSUE TITLE
Mediates binding to actin in host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#165]
Some parasite proteins bind host actin, some of them then do something but others do not appear to. I think this activity should be noted. There doesn't appear to be a GO term that just covers actin binding (I did a quick search in AmiGO but found nothing.  This term would be useful to distinguish factors that bind actin versus those factors that bind something else but that _affect_ actin.

For new term requests, please provide the following information:
## Preferred term label
Mediates actin binding in host cell

## Textual definition
These gene products mediate the association with actin, either filamentous or globular, in the host cell.

## Suggested parent term
This term should be a child of a new term "mediates binding to host cytoskeletal component"

## Attribution
https://orcid.org/0000-0002-5702-4690

Some proteins that bind host cytoskeletal components

1. SseI binds to the actin cross-linking protein filamin to colocalize with polymerizing actin in the cytoskeleton [PMID12675800].
2. Gonococcal Porin B binds host actin.
3. Streptococcal inhibitor of complement (Sic) enhances survival of the bacterium by binding to the host plasma membrane protein ezrin. This inhibits the efficient internalization and destruction of Streptococcus by polymorphonuclear leukocytes since it interferes with small GTPase signaling to the actin cytoskeleton [PMID12679262]. 
4. VopF of Vibrio cholera functions primarily as an actin nucleation factor. It associates briefly (∼100 s) with the pointed end. VopF has tandem WH2 domain–based nucleators like Sca2 from rickettsiae [PMID28363971]. 
5. VopL of Vibrio parahaemolyticus is inhibited by host profilin and it interacts directly with actin to provoke rapid cycles of filament nucleation and detachment [PMID21873985].
6. VopV of Vibrio parahaemolyticus binds directly to filamentous actin, despite the lack of a known actin binding motif. Once injected into the epithelial cells of the gut, VopV has enterotoxic activity. The enterotoxic activity correlates with the actin binding but not the actin bundling activity of VopV [PMID22018240].

**Comment by jproesch** [comment]
@genegodbold are these modulating cytoskeleton? Looking at 'modulates cytoskeleton in host cell' <http://purl.obolibrary.org/obo/PATHGO_0000028> as parent term for mediates binding to host cytoskeletal component

**Comment by genegodbold** [comment]
@jproesch Yes, all the things that mess directly with cytoskeletal monomers (actin and tubulin at least--I don't think anything messes with keratin that I remember) will also necessarily have effects on the resulting cytoskeleton.
