### ISSUE TITLE
Mediates inhibition of nitric oxide radical production

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#168]
I think there is a place for something that inhibits host nitric oxide synthase to accommodate:

1. PPE2 from M. tuberculosis inhibits host nitric oxide production by binding to the iNOS promoter. 
2. When a mutant M. smegmatis bacterium expressing PE_PGRS62 is used to infect murine macrophages, it inhibits expression of iNOS which synthesizes the bactericidal NO [PMID23167250]. 
3. When PE15 is expressed in the nonpathogenic M. smegmatis and used to infect cultured macrophages, the bacteria down-regulate expression of host iNOS and trigger activation of the host MAP kinases leading to production of the anti-inflammatory cytokine interleukin-10 [PMID23284742]. 
4. When PE5 is expressed in the nonpathogenic M. smegmatis and used to infect cultured macrophages, the bacteria down-regulate expression of host iNOS and trigger activation of the host MAP kinases leading to production of the anti-inflammatory cytokine interleukin-10 [PMID23284742].

For new term requests, please provide the following information:
## Preferred term label
Mediates inhibition of nitric oxide radical production

## Synonyms
None

## Textual definition
These proteins decrease the production of host nitric oxide radicals, promoting survival of the parasite, particularly in macrophages.

## Suggested parent term
The parent term should be: PATHGO_0000164 Disrupts cellular metabolism

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Looks like under 'mediates immune evasion and subversion' we have 'mediates free radical detoxification'.  Agree that inhibiting NO radical production is different to detoxification, so we will add a term for this.

**Comment by jproesch** [comment]
@genegodbold @jacakrj1 'inhibits nitric oxide synthase' <http://purl.obolibrary.org/obo/pathgo/PATHGO_0000354> is already a child class to 'modulates reactive oxygen species levels' <http://purl.obolibrary.org/obo/pathgo/PATHGO_0000353> under PATHGO_0000164 Disrupts cellular metabolism.  Is this sufficient?

**Comment by genegodbold** [comment]
@jproesch It shouldn't just be "inhibits nitric oxide synthase"--that's too narrow. It should "inhibit nitric oxide **production OR activity**" which takes into account both transcriptional downregulation AND signaling legerdemain to decrease production.

**Comment by jproesch** [comment]
@genegodbold created new term 'inhibits nitric oxide radical production' <http://purl.obolibrary.org/obo/PATHGO_0000376> and made inhibits nitric oxide synthase' http://purl.obolibrary.org/obo/pathgo/PATHGO_0000354 a subclass
