### ISSUE TITLE
consider anticoagulation terms

### ISSUE THREAD

**Issue by jproesch** [jhuapl-bio/pathogenesis-gene-ontology#171]

**Comment by genegodbold** [comment]
These are the only examples I have that mention coagulation:

- Coagulation targeting metallo-endo peptidase of Acinetobacter baumannii (CpaA) is a T2SS effector  zinc-dependent metalloprotease that can cleave host fibrinogen (the A-alpha chain) and host factor V which are involved in contact-activated clotting. CpaA cuts factor V in a dose-dependent manner to inhibit blood clotting [PMID24910020]. The human coagulation factor XII (fXII) is also a substrate of CpaA which cuts factor XII in a highly glycosylated area. By inactivating fXII, CpaA may attenuate important antimicrobial defense mechanisms such as intravascular thrombus formation, thus allowing A. baumannii to disseminate [PMID30563903].
- InhA of Bacillus anthracis is a secreted zinc metalloprotease that cleaves host proteins involved in the coagulation cascade potentially helping the pathogen to disseminate through the circulatory system [PMID22452315]. Purified InhA extracted from B. anthracis and introduced via the intravenous route caused an increase in blood brain barrier permeability as measured by marker dye uptake into mouse brain tissue. An InhA producing B. anthracis strain, as well as a B. subtilis strain genetically modified to produce InhA induced a decrease in trans-endothelial electrical resistance in HBMEC monolayers. A Bacillus anthracis strain in which the gene encoding InhA was missing was attenuated in virulence compared to an InhA producing strain in a late infection mouse disease model. Mice injected intravenously with vegetative B. anthrax cells lacking InhA displayed a prolonged mean time to death and only one subject in the study group, compared to five when the InhA positive strain was used, showed high bacterial counts in the brain [PMID21437287].
- EspP from E. coli can cut human coagulation factor V [PMID9194704].
- Bone sialoprotein-binding protein from Staphylococcus aureus is a glycoprotein of nearly 1200 residues  that adheres to human bone sialoprotein [PMID10642520]. Bbp expressed on the surface of bacterai mediates adherence to the alpha chain of human fibrinogen (UniProtP02671) isolated from plasma but not to fibrinogen from other species. Bbp recognizes residues 561-575 of the Fg alpha chain with a dissociation constant of 540 nanomolar. Bbp binding to human fibrinogen inhibits thrombin-induced blood coagulation [PMID21642438].

**Comment by jproesch** [comment]
@genegodbold seems the first two, and possibly the third, examples above inhibit coagulation to ultimately promote dissemination. 
Propose "inhibits coagulation in host" as subclass to "mediates dissemination"

**Comment by genegodbold** [comment]
@jproesch I don't think the two are inherently related, though they can be functionally related. So I wouldn't make one dependent on the other. Plenty of harm can be done by something that "inhibits coagulation in other organism" which is how you could phrase it if you wanted to be able to annotate snake toxins as well as bacterial factors.
