### ISSUE TITLE
consider interferon terms

### ISSUE THREAD

**Issue by jproesch** [jhuapl-bio/pathogenesis-gene-ontology#173]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
(e.g., Asplenia)

## Synonyms
(e.g., Absent spleen)

## Textual definition
the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term
Please look at the hierarchy in the Protege browser, and provide the PathGO id or rdfs:label of the suggested parent term.

## Attribution
If you would like a nanoattribution, please indicate your ORCID id.

**Comment by genegodbold** [comment]
Hey @jproesch, I have a number of sequences that could use this term. I think it should include manipulation of TANK-binding kinase 1 (TBK1) which, upon activation,  phosphorylates interferon response factor 3 which then dimerizes, moves to the nucleus, and activates type I interferon genes. Viral sequences that mess with TBK1 or just one step upstream include: IE62 from varicella zoster,  K7 and N1L from vaccinia, VP35 from Marburg, MC159 from molluscum contagiosum, NSP3 from SARS-CoV, nucleocapsid protein, NSP6, NSP13, and ORF9b from SARS-CoV-2,

**Comment by jproesch** [comment]
@genegodbold can you propose possible term labels?  somehting like "stimulates Type Iinterferon expression"?

**Comment by genegodbold** [comment]
@jproesch See issue #233
