### ISSUE TITLE
Host ZBP1 signaling disruption factor

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#174]
ZBP1 is targeted by several DNA viruses and the influenza virus that replicates in the host nucleus. After associating with some factor, probably viral, ZBP1 associates with TBK1 and IRF3 and regulates activation of IRF3 and induction of type I IFNs. It also activates necroptosis through host inflammasomes. ZBP1 sensing of influenza virus can occur either in the nuclear or cytoplasmic compartments (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5863909/) 

1. Varicella zoster virus employs one of these (ORF20) [PMID32649716] 
2. So does herpes zoster virus [PMID32060646].
3. Here is a _bacterial protein_ that messes with it: EspL from E. coli is a T3SS LEE effector cysteine proteinase (Cys47/His131/Asp153) that degrades the host RHIM-containing proteins RIPK1, RIPK3, TRIF and ZBP1/DAI within the RHIM region during infection with Escherichia coli. Proteins that contain receptor interacting protein (RIP) homotypic interaction motifs (RHIM) play a key role in cell death and inﬂammatory signaling. Bacterial infection and/or ectopic expression of EspL leads to rapid inactivation of RIPK1, RIPK3, TRIF and ZBP1/DAI and inhibition of tumor necrosis factor (TNF), lipopolysaccharide or polyinosinic:polycytidylic acid (poly(I:C))-induced necroptosis and inﬂammatory signaling.  In vivo, EspL cysteine protease activity contributes to persistent colonization of mice by the EPEC-like mouse pathogen Citrobacter rodentium. EspL designates a family of T3SS cysteine protease effectors found in a range of bacteria and reveals a mechanism by which gastrointestinal pathogens directly target RHIM-dependent inﬂammatory and necroptotic signaling pathways [PMID28085133]. 

For new term requests, please provide the following information:
## Preferred term label
Host ZBP1 signaling disruption factor

## Synonyms
None

## Textual definition
Parasite proteins that interfere with ZBP1 signaling by interfering with its (1) abundance (2) ubiquitination status (3) interaction with downstream signaling partners (perhaps through the RHIM motif) including (host) RIPK1 or (host) RIPK3 or (4) with the binding dynamics of the protein complex that includes ZBP1, RIPK1/RIPK3, FADD and caspase-8.

## Suggested parent term
PATHGO_0000090 (immune evasion and subversion factor)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Will probably add this term, but have to think about organization.  We already have 'disrupts host TNFR signaling'.  First thought was we should add a 'disrupts host cellular signaling' term and make TNFR and ZBP1 subclasses.  But we already have a 'disrupts host cellular signaling' term elsewhere.

**Comment by jproesch** [comment]
@jacakrj1 @genegodbold I'm leaning towards putting this under PATHGO_0000165 disrupts host cellular signaling

**Comment by genegodbold** [comment]
@jproesch That would be fine, but ZBP1 is part of host immune defense. The immune system is all about signaling the appropriate response so it doesn't make sense to have dividing lines between "immune subversion" and "host signaling".

**Comment by jproesch** [comment]
@genegodbold gotcha.  So possibly "disrupts host immune signaling" as a new parent class to 'disrupts host TNFR signaling' and add the sibling class 'disrupts host ZBP1 signaling'.

**Comment by genegodbold** [comment]
@jproesch That could work--there are plenty of things in the immune system that are involved in lots of other biological things. So maybe host cell signaling **should** be the parent without reference to the immune system. There are developmental pathways that "borrow" immune signaling pathways--but that should probably be the other way around.
