### ISSUE TITLE
Enhances host inflammasome activation

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#176]
For new term requests, please provide the following information:
## Preferred term label
Enhances host inflammasome activation

Examples:

1. Alpha-hemolysin from Staphylococcus aureus activates pyrin domain containing 3 inflammasome (NLRP3) to induce production of interleukin-1beta and pyroptosis. NLRP-3 induced necrosis causes severe pulmonary injury and pneumonia in its host. Nlrp3-/- mice showed significantly lower mortality than wild-type mice [PMID22279123]. 
2. Anthrax lethal factor activates the host nucleotide-binding domain leucine-rich repeat pyrin domain-containing 1B (NLRP1B) inflammasome by cleaving NLRP1B after Lys44 (PMID30872531].
3. Cytolethal distending toxin of Aggregatibacter actinomycetemcomitans activates host caspase-1 via the NLRP3 inflammasome in macrophages [PMID25644004].
4. HBL enterotoxin of Bacillus cereus activates the NLRP3 inflammasome with secretion of IL-1beta and IL-18 and instigation of pyroptosis. Inhibition of the inflammasome prevented B. cereus-induced lethality. Inflammasome activation was a requirement for mortality [PMID30531979].
5. Both TcdA and TcdB of Clostridioides difficile are able to activate the inflammasome to secrete interleukin-1beta with TcdB able to induce inflammasome activation at much lower concentrations than TcdA [PMID20398664]. TcdA induction of the inflammasome in infected cells is dependent on its ability to glucosylate the host Rho protein. This glucosylation is absolutely required for tissue damage and an inflammatory response in vivo [PMID27271747].
6. Cell transolcating kinase A (CtkA) of Helicobacter pylori induces production of pro-inflammatory cytokines (TNF, IL-6, IL-1 beta) in gastric epithelial cells via activation of the host inflammasome [PMID25172221].
7. PPE13 of Mycobacterium bovis and M. tuberculosis is involved in activating the host NLRP3 inflammasome, inducing host IL-1beta secretion and caspase-1 cleavage when heterologously expressed in M. smegmatis. Assembly of the NLRP3 inflammasome complex was facilitated by PPE13 acting through the LRR and NATCH domains of NLRP3. PPE13s from M. tuberculosis, M. bovis, and M. marinum acted similarly [PMID32738179].
8. The CARDS toxin of Mycoplasma pneumoniae activates the host NLRP3 inflammasome by directly ADP-ribosylating it. This leads to subsequent release of interleukin-1beta and associated pathologies [PMID25538194].

## Synonyms
None

## Textual definition
These parasite proteins directly and specifically enhance inflammasome activation beyond what would normally occur as a result of a parasitic infection.

## Suggested parent term
The parent term should be "modulates host inflammasome activation"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Related to issue #175
