### ISSUE TITLE
Filling in extracellular matrix binding with two new terms

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#178]
I see a need for two new terms as children under the parent PATHGO_0000099 (mediates extracellular matrix binding)

1. Mediates host collagen binding
2. Mediates host fibronectin binding

There are three terms there already (for vitronectin, glycosaminoglycan, and laminin binding)

Currently there are five terms under PATHGO_0000077 (extracellular matrix binding factor)
- PATHGO_0000069 (collagen binding protein)
- PATHGO_0000133 (fibronectin binding protein)
- PATHGO_0000245 (vitronectin binding protein)
- ATHGO_0000272 (host glycosaminoglycan-or proteoglycan-binding factor)
- PATHGO_0000274 (laminin binding protein)

...so this correction is simply providing the requisite pairing for those five terms.

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Determinant branch terms, issue no longer relevant.
