### ISSUE TITLE
PATHGO_0000072 (glycoprotein binding) placement and integrin 

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#179]
So "glycoprotein binding" is a child under PATHGO_0000211 (mediates cell surface binding)

Every other child term is preceded by "mediates"
- mediates integrin binding
- mediates cholesterol binding
- mediates carbohydrate binding

Perhaps "glycoprotein binding" should be placed under the parent PATHGO_0000198 (cell surface binding factor) --which should probably be called "host cell surface binding factor" which has the children:
- integrin binding protein
- cholesterol binding factor
- carbohydrate binding factor

In either place, _integrin_ is the most specific feature and it seems like it should be under, in both parents, "glycoprotein binding" or "mediates glycoprotein binding". 
(Because integrin **is** a glycoprotein. It binds laminin and other things.)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Indeed, integrin binding is a form of cell surface glycoprotein binding.  Not sure how we missed that one.  Will commit fix shortly.
