### ISSUE TITLE
Need a term that encompasses toxin synthases, including mycotoxin synthases

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#191]
So this isn't needed for protein toxins which are directly encoded, but rather for synthases that make non-protein, or partially-protein toxins that need to be built. These are obviously of relatively low threat, but there should be a way of designating them. Obviously these will only be threatening if they are all present in a microbe or organism. The SME panel gave us some of these from plants including Hemp and the Coca plant.

For new term requests, please provide the following information:
## Preferred term label
Contributes to the formation of a product that is toxic for another organism. 
[This might break some rules by having consequences built in, so it may be inadvisable to have, ontologically speaking.]

**Problems**: 
- We make reactive oxygen and nitrogen species that are toxic for bacteria so could/should those enzymes be labeled with these terms?
- There are a bajillion plants that make things that are toxic for humans and insects. Do the enzymes involved in their synthesis get tagged with this term?
- The target of the synthesized toxin should be specified for every use of this term. Is this practical?

## Textual definition
This term encompasses synthases that contribute to the production of molecules that are toxic or otherwise pharmacologically potent for *other* organisms.

Examples from _Cannabis sativa_: 
1. Chalcone synthase-like protein 1 (CAN383): This hemp protein is a chalcone synthase that may use malonyl-CoA and hexanoyl-CoA as substrates but without producing olivetol or olivetolic acid. CAN383 plays a role in the synthesis of THCA [PMID19581347]. 
2. Tetrahydrocannabinolic acid synthase: THCA synthase catalyzes the oxidative cyclization of the monoterpene moiety in cannabigerolic acid (CBGA), producing delta9-tetrahydrocannabinolate (THCA), the major cannabioid in drug-type Cannabis sativa plants. THCA can use cannabinerolic acid as substrate, but not cannabigerol or cannabinerol [PMID15190053].

Other organisms
1) Decarboxylase DEC1 from Cochliobolus heterostrophus (Bipolaris maydis): T-toxin is a mycotoxin that is phytotoxic and synthesized by at least three genes each at two loci (Tox1A and Tox1B) in Cochliobolus heterostrophus race T. DEC1 catalyzes the decarboxylation of the penultimate product [PMID20192833].
2) Phenylpropionate dioxygenase (SxtT) from Cylindrospermopsis raciborskii T3: The sequence encoding phenylpropionate dioxygenase has been acquired by cyanobacteria through horizontal gene transfer. SxtT plays a role in the complicated synthesis of saxitoxin [PMID19484122].
3) Methylecgonone reductase from Erythroxylum coca (Coca plant): The enzyme methylecgonone reductase converts methylecgonone (2-carbomethoxy-3-tropinone) to methylecgonine (2-carbomethoxy-3beta-tropine), the penultimate step in cocaine biosynthesis. The protein is expressed in young expanding leaves of the plant and is not found in root tissue [PMID22665766]. 
4) ClbO from Escherichia coli: ClbO is one of three polyketide megasynthases involved in colibactin synthesis. ClbO may be the final enzymatic module of the assembly line [PMID29642622]. Colibactin is a cyclomodulin and a genotoxin that results in dsDNA breaks, chromosomal problems, and cell cycle arrest at G2/M [PMID16902142]-[PMID20534522].

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold I think this is what PATHGO_0000337 intends to cover "mediates toxin synthesis"
