### ISSUE TITLE
Transcription factor (of a pathogenic organism) that modulates the expression of genes that affect pathogenicity

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#192]
I realize this is vague, but it is the best I can formulate right now. We need a term for virulence that identifies a gene product as involved in controlloing/regulating pathogenesis and takes away the temptation to apply all the ontology terms of the *regulated genes* to the transcription factor.

For new term requests, please provide the following information:
## Preferred term label
Transcription factor of a parasite that modulates the expression of genes that mediate pathogenesis in a host

## Textual definition
This gene product acts as a transcription factor in a parasite that modulates the expression of genes of that parasite that are pathogenic for a host.

**Examples**:
1) Global transcription regulator FGP1 of Gibberella zeae (Wheat head blight fungus): FGP1 regulates many genes involving trichothecene toxin accumulation and several other pathogenic processes in Gibberella zeae. There are orthologs in other fungi [PMID22693448].
2) Macrophage locus protein A (MglA) of Francisella tularensis: MglA and the stringent starvation protein A (SspA) interact with RNA polymerase and the pathogenicity island gene regulator (PigR) to activate transcription of the Francisella pathogenicity island [PMID26121147]-[PMID20445258].
3) Histidine kinase GraS of Staphylococcus aureus: The two-component regulatory system GraRS positively regulates expression from the dltABCD operon which is responsible for the modification of negatively charged phosphate groups in the backbone of teichoic acids with D-alanine. This reduces bacterial surface charge and renders the bacterium more resistant to antimicrobial peptides and certain antibiotics [PMID18518949].
4) Velvet complex subunit 2 of Botryotinia fuckeliana (This organism makes me pause every time I see the name): This is a component of the velvet transcription factor that influences development and is involved in resistance to oxidative stress. It may play a small and indirect role in the ability of the fungus to cause disease but this is not entirely clear [PMID25625818].
5) pH-response transcription factor pacC/RIM101 from Aspergillus parasiticus: This is a transcription factor of the opportunistic pathogenic fungus Aspergillus parasiticus. It may play a role in the regulation of the aflatoxin biosynthetic pathway [PMID10095064]-[PMID10919326].

## Suggested parent term
I'm going to leave this to you folks as you know the hierarchy better than me.

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold this should work in the indirect branch, "modulates expression of genes that mediate pathogenesis in host" seems really long and wordy, but should work.
