### ISSUE TITLE
"Mediates destruction of host extracellular matrix" and other terms

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#193]
For Atrolysin-E from Crotalus atrox (some rattlesnake): This proteolytic toxin degrades extracellular matrix proteins [PMID2817904].  Rattlesnake hemorrhagic toxin can disable the circulatory system by inhibiting platelet aggregation [PMID9637732].

There is a term for PATHGO_0000226 (disrupts extracellular matrix) but it is under "PATHGO_0000235 (mediates host cell invasion)" or maybe this is a mistake of how I formatted it. This pertains directly to issue #154 .
See also issue #113 .

I see how a protease that destroys the extracellular matrix can lead to greater dissemination of a bacterial pathogen--there are staphylococcal proteases involved in scalded skin syndrome that do this, but disruption probably isn't going to be associated with host cell *invasion*, at least I don't think I remember seeing this as common. I don't think extracellular matrix destruction has to be associated with either *invasion* OR *dissemination*. The latter is probably complementary but not dependent on it. (Again, please disregard if this critique is based on my mis-formating it.)

**Suggestion for How to Handle Tissue Destruction**
How about add a "Destruction of tissue in other organism" child under parent "Mechanism of pathogenicity" then under that have these five children:
1) Mediates destruction of host extracellular matrix [This for virulence factors]
2) Mediates destruction of extracellular matrix in other organism [This for toxins]
3) Mediates release of host cell from host extracellular matrix [This is essentially the "cytopathic" effect.]
4) PATHGO_0000161 (mucosal barrier disruption) [This would be moved from parent PATHGO_0000159 (disrupts cellular adhesion) since it does not necessarily deal with 'cellular' adhesion but rather cell-matrix adhesion].
5) PATHGO_0000162 (epithelial layer disruption) [This would be moved from parent PATHGO_0000159 (disrupts cellular adhesion) since it does not necessarily deal with 'cellular' adhesion but rather cell-matrix adhesion].

## Suggested parent term
"Destruction of tissue in other organism" should be a child of parent PATHGO_0000114 (mechanism of pathogenicity)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold fair to append "structure" here to the proposed parent, i.e. destroys (disrupts?)  tissue structure

**Comment by genegodbold** [comment]
@jproesch "mediates disruption of tissue structure in other organism" sounds good for the parent; a lot of snake venom components can then be placed under that
