### ISSUE TITLE
Chaperone for a pathogenic factor

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#194]
While there is a way to designate secretion system components, there isn't a way to designate a gene product that acts as a chaperone for a protein effector or a toxic component. The protein chaperone protects its ward protein. See also issue #134 
Examples:

1. Phospholipase A2 homolog crotoxin acid subunit CA from Crotalus durissus terrificus (South American rattlesnake): This rattlesnake venom component is not toxic in itself but potentiates the lethal potency of the other two constituents of a heterotrimer: CA and CB which are lethal presynaptic neurotoxins that block neuromuscular transmission [PMID21787789].
2. Botulinum neurotoxin type C1 nontoxic-nonhemagglutinin component (CST085; NTNHA) from Clostridium botulinum phage: This protein is nearly identical to NTNHA which complexes with the botulinum toxin to protect it from destruction in the gastrointestinal tract, serving as a chaperone [PMID22363010].
3. Acidic phospholipase A2 RV-7 from Daboia siamensis (Eastern Russel's viper) (P31100): As a monomer, this snake venom component has *low* enzymatic activity. It may **facilitate** the binding of venom component RV-4 to presynaptic binding sites, _acting as a chaperone and minimizing the destruction of RV-4 by binding to extraneous targets_. The RV-7/RV-4 heterodimer targets presynaptic sites at the neuromuscular junction [PMID8835338].

For new term requests, please provide the following information:
## Preferred term label
Chaperone for a pathogenic factor

## Textual definition
This gene product is indirectly involved in pathogenesis as it accompanies a virulence factor or toxin along its journey to the host or target, protecting it from harm and helping direct it to its site of activity.

## Suggested parent term
Maybe this could be a child under parent term PATHGO_0000102 (determinant of protein effector secretion), but maybe this doesn't make sense.

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Adding a new term 'modulates virulence factor activity' to represent this mechanism.

**Comment by genegodbold** [comment]
Nice!
This is more generic than the bacterial effector so it can cover venom components. I know you know this, but I process things by writing sometimes.
