### ISSUE TITLE
evaluate label of 'deISGylating activity' <http://purl.obolibrary.org/obo/PATHGO_0000330>

### ISSUE THREAD

**Issue by jproesch** [jhuapl-bio/pathogenesis-gene-ontology#197]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
(e.g., Asplenia)

## Synonyms
(e.g., Absent spleen)

## Textual definition
the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term
Please look at the hierarchy in the Protege browser, and provide the PathGO id or rdfs:label of the suggested parent term.

## Attribution
If you would like a nanoattribution, please indicate your ORCID id.

**Comment by jacakrj1** [comment]
Updated the label.  Just need you to merge the PR.
