### ISSUE TITLE
Designating effectors (bacterial, fungal, protozoal) secreted via microbial secretion systems

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#200]
I think it would be useful to be able to designate secreted effectors. This is going to be hard without the "determinant branch", though.

For new term requests, please provide the following information:
## Preferred term label
Secreted protein effector

## Textual definition
These gene products are secreted from the synthesizing cell either into the extracellular milieu or directly into another cell of a different type. These gene products exert specific effects on or in a target cell.

## Suggested parent term
Maybe PATHGO_0000114 (mechanism of pathogenicity)?

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold agree it will be difficult to fit this within the scope.

**Comment by genegodbold** [comment]
@jproesch It would be useful to have a "bin" that has "secreted bacterial effectors", but I don't know how to get us there in the existing ontology--we can keep thinking about it. Secreted effectors have a huge role in **both** bacterial pathogenesis **and** intra-bacterial warfare.

**Comment by genegodbold** [comment]
@jproesch Here is an complicated solution, a new term: "mediates effects in other organism following secretion from parasite". This **would** be a way of identifying secreted effectors that mess with the molecules of other organisms.

**Comment by jproesch** [comment]
@genegodbold if you will use it...I will add it.  :)

**Comment by genegodbold** [comment]
@jproesch Amen, sister. 
:-)
