### ISSUE TITLE
Reconsider PATHGO_0000177 (modulates second messenger molecules) and PATHGO_0000228 (disrupts second messenger levels/abundance)

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#210]
Nearly everything in a signaling pathway is a "second messenger molecule" so these seem too broad as terms. I haven't (yet) had occasion to use them.

## Suggested parent term
Please look at the hierarchy in the Protege browser, and provide the PathGO id or rdfs:label of the suggested parent term.

## Attribution
If you would like a nanoattribution, please indicate your ORCID id.

**Comment by jproesch** [comment]
@genegodbold missed this one! Not sure how we missed this duplication.  I will remove both if they are too broad and not useful.  We had examples: cyclin-dependent kinase 1 inactivator; calcium- and calmodulin-dependent adenylate cyclase as possible examples in the notes, but these could likely be covered by more spcific terms if needed.
