### ISSUE TITLE
Ligand for host microbial-associated molecular pattern receptor/pattern recognition receptors

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#211]
I have come to feel that we ought to recognize the inflammatory possibilities of sequences of concern that naturally ligate/agonize host innate immune receptors.  This is related to issue #166. 

- Bacterial flagellin is a ligand for mammalian TLR5.
- Spike glycoprotein of SARS-CoV-2 appears to be a ligand for TLR2 [PMID33758854], and maybe TLR4 as well [PMID33644468]. The question is whether this is "natural" and benefits the host? Or is it an example of viral manipulation of the receptor for its own ends? There are both bacterial and viral examples of this--many of them, but these should be classified under:	**PATHGO_0000233 (disrupts host toll-like receptor signaling)** AND **PATHGO_0000176 (regulation of host receptor activity)**

## Preferred term label
Ligand for host microbial-associated molecular pattern receptor/pattern recognition receptors

## Textual definition
These parasite sequences are natural/evolved ligands for host microbial-associated molecular pattern (MAMP) receptors. These host receptors include membrane-bound Toll-like receptors (TLRs), cytoplasmic NOD-like receptors (NLRs), membrane-bound C-type lectin receptors, cytoplasmic absent in melanoma 2-like receptors (AIM2) and retinoic acid-inducible gene-I-like receptors (RLRs). See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6298609/. Many of these do not ligate proteins but rather recognize nucleic acid sequences in odd places in the cell, or carbohydrates, or lipids, or combinations thereof.

The ligation event is one that is "meant" to happen by the host. It leads to host cell recognition of the presence of a trespassing microbe and results in the activation of proinflammatory signaling and host transcription to make the intracellular environment, and, eventually, the extracellular environment, less hospitable for the interloper.

## Suggested parent term
I am not sure where to put this. "Mechanism of pathogenicity" does not seem appropriate as this event is something intended to restore homeostasis, though it will disrupt things in the short term.

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold this is a tricky one, I read these as being recognized by host immune system, but not to any clear benefit to the pathogen. Seems out of scope for mechanism of pathogenicity (although I do agree that host immune system can lead to parthenogenesis in the host).

**Comment by genegodbold** [comment]
@jproesch I totally agree; this isn't a mechanism of pathogenicity, but it is good to note for those who care about pathogenicity. These things are easily confused with something that induced inflammation.

**Comment by genegodbold** [comment]
I think this can be fulfilled by #250
