### ISSUE TITLE
What is PATHGO:0000253 (mediates host barrier traversal) intended for?

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#212]
It seems to me that this term should be used for things that break open a tissue or the space between cells, either transiently or permanently (via proteolytic cleavage, say). And it could also be used for viral movement proteins that allow the crossing of intracellular barriers that couldn't otherwise be breachable. In this sense all dissemination factors might be candidates for this term. But I see that you have applied this to protective antigen which allows lethal factor and edema factor to get into a cell. I don't think you want to contaminate the term with adhesive/invasive components that allow mere cell entry.

**Comment by jproesch** [comment]
@genegodbold your interpretation of intention is correct, we will review that preliminary annotation.
