### ISSUE TITLE
New term suggestion: Mediates symbiont survival in host

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#217]
You folks might want to consider adding a "mediates survival in host" for things that do not obviously harm the host but are merely required for the continued existence of the parasite. If something is going to be necessary both *inside* and *outside* the host, I do not understand how it can be considered pathogenic.

Under the "mediates survival in host" you can put "mediates metal cofactor acquisition" and all the nutrient acquisition terms.

This is related to issue #204 

For new term requests, please provide the following information:
## Preferred term label
Mediates symbiont survival in host

## Textual definition
This term includes gene products that mediate symbiont survival in host but that are not necessarily involved in host damage or immune subversion. If the gene product enhances or enables properties that would be necessary for the symbiont to survive in any environment, then this gene product cannot be said to be necessary for pathogenesis.

## Suggested parent term
The parent term should NOT be "mechanism of pathogenicity"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold I think this makes sense, but we currently don't have a place for things that don't fall under mechanism of pathogenicity (either directly or indirectly) as they have been defined as out of scope. 'Mediates proliferation and survival' (PATHGO_0000150) is already the parent term, but could be changed to 'Mediates survival in host' as I'm not sure anything currently under that term is specific to proliferation (and terms shouldn't have "and" in label). This still keeps these terms as Indirect mechanisms though, so isn't really a change...

**Comment by genegodbold** [comment]
@jproesch How do you define a mechanism of pathogenicity? If these sequences that enable parasite survival, are found in both pathogenic and nonpathogenic species, and do not interact with host proteins, can they reasonably be assumed to a mechanism of pathogenicity? I'm dubious...

**Comment by jproesch** [comment]
@genegodbold Current definition: "A mechanism of pathogenicity is a means by which a damaging effect is brought about, and that specifically describes how that effect is exerted."  Then we have Direct and Indirect branches.  These are currently under indirect.  However, don't seem to fit the editorial comment "Plays a supporting role for pathogenesis to other gene products. Note, functions related to the normal growth processes of pathogens like 'sporulation' should not be annotated with this term.  Only genes that are necessary for pathogenesis, like 'secretion systems', should be annotated with this term."  Seems to argue for removing most of the proliferation and survival terms, except the antibiotic resistance term.

**Comment by genegodbold** [comment]
@jproesch This does seem to be an argument for leaving them out. There might be wailing and gnashing of teeth in certain quarters of the microbial pathogenesis realm. Or not. Survival factors/proliferative factors don't result in a damaging effect, they are necessary for the parasite but indifferent regarding the host.
