### ISSUE TITLE
Parasite nucleic acid binding in host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#24]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Binds parasite nucleic acid in host cell

## Synonyms
None

## Textual definition
Viral proteins can sequester their own nucleic acid, typically dsRNA, to conceal it from host pathogen recognition receptors. 

## Suggested parent term
[I am not sure. This is more of a molecular function sort of activity, but these things are trying to conceal viral parasite signals from immune surveillance.]

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
I think this concept of "evasion from [intracellular] pattern recognition receptors" will end up getting addressed by some of the other evasion of immune response terms.  But RNA (e.g. viral dsRNA) binding doesn't feel like a mechanism of *pathogenesis* to me, so I'm inclined to leave it out.  Will bring it up at our next PathGO meeting (next week).

**Comment by genegodbold** [comment]
It is a method of thwarting immune surveillance. Hiding is certainly an aspect of pathogenesis. It doesn't damage the host, but then neither does adherence or invasion. These mechanisms avoid activating the immune response by concealing the offending molecule. It is akin to AprA/serralysin from Pseudomonas aeruginosa. Serralysin cuts up bacterial flagellin monomers so it can't be detected by host TLR5 [PMID22131330]. These viral dsRNA binding proteins--and there are several in poxviruses--sequester the dsRNA so that TLR3 doesn't recognize it. You would consider things that interfere with antigen display (either by altering the TAP complex or messing with proteasomes) to be pathogenic, right? It is the same sort of thing.
