### ISSUE TITLE
Nomenclature "fix"

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#240]
So I've been attending the multiorganism GO meetings that are all but one Monday per month. Three things I've learned about nomenclature

1. Don't mention "host" or "parasite" in a term name
2. Instead refer to activity/process "in another organism"
3. Use "suppresses" or "suppression" instead of "inhibits" or "inhibition"

I have been modifying the terms as I go along to hew to these standards. Eventually, you'll see the final results, though probably not until close to Thanksgiving.

**Comment by jacakrj1** [comment]
These changes were all addressed in the October 26 updates PR #408, so closing this issue out.
