### ISSUE TITLE
Host complement inactivation factor, direct

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#34]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Host complement inactivation factor, direct

## Synonyms
None

## Textual definition
This parasite enzyme inactivates host complement through direct enzymatic activity that inheres in the parasite sequence.

## Suggested parent term
Complement system inhibition factor

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@kzudock Please add Direct host complement inactivation factor as determinant term and Direct host complement inactivation as mechanism term.
