### ISSUE TITLE
Host complement inactivation factor, indirect

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#35]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Host complement inactivation factor, indirect

## Synonyms
None

## Textual definition
This parasite protein inactivates host complement indirectly by recruiting a host enzyme, typically a proteinase, to the parasite surface.

## Suggested parent term
Complement system inhibition factor (PATHGO_0000153)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@kzudock Please add Indirect host complement inactivation factor as determinant term and Indirect host complement inactivation as mechanism term.

**Comment by jproesch** [comment]
@kzudock Please add Direct host complement inactivation factor as determinant term and Direct host complement inactivation as mechanism term.
