### ISSUE TITLE
Binds host complement control protein

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#36]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Binds host complement control protein

## Synonyms
None

## Textual definition
This parasite protein inhibits host complement activation by recruiting host complement control proteins to the surface of the parasite.

## Suggested parent term
Complement system inhibition factor (PATHGO_0000153)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by kzudock** [comment]
Term added as PATHGO_0000249
