### ISSUE TITLE
Proposed term obsolescence: PATHGO:0000324 (inactivates complement by recruiting vitronectin)

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#368]
There are few cases where parasite recruitment of host vitronectin seems to be involved in complement inactivation. I think this term might be needlessly specific. There are at least a dozen bacterial sequences that **bind** host vitronectin. These can be noted under a "mediates binding to host vitronectin" term.

**Comment by jacakrj1** [comment]
Agree that this term is very specific, but as you say there are examples of it (and we have a reference for the term), so I'm leaving it in.
