### ISSUE TITLE
Consider expanding PATHGO_0000214 (tight junction modification) to (modification of host tight junction or adherens junctions)

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#40]
The cytoskeletal architecture of tight and adherens junctions is similar and both contribute to barrier function, particularly in the intestinal epithelial apical junctional complex.

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Briefly considered broadening this term to 'junctional complex modification', and then making 'tight' and 'adherens' subclasses of it, but I prefer your suggestion of combining them.  We may have to reconsider (or at least make a new parent class) if we find a pathogen that relies on altering desmosome junctions, though.
