### ISSUE TITLE
Term name improvement: PATHGO:0000384 (mediates effect within cells of an organism following secretion from another organism)

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#405]
This term is meant to designate all bacterial toxins and secreted effectors as well as effectors of other parasites.

The term may be so broad that it also includes secreted venoms but that is not the intent since it would dilute the usefulness.

**Comment by jacakrj1** [comment]
I'm actually going to delete this term altogether since it doesn't convey a mechanism of pathogenesis.  It's just too vague. Presumably there are other terms that can be used to annotate genes that would have been annotated with this term.

**Comment by genegodbold** [comment]
I've used it to annotate over 500 bacterial effectors

**Comment by jproesch** [comment]
@jacakrj1 this should be kept if it is useful.  Was it removed in the pending pull request?
