### ISSUE TITLE
Reconsider PATHGO_0000207 and PATHGO_0000220 dealing with inflammatory cytokine suppression

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#44]
These terms both concern the suppression of inflammatory cytokines at a level that may be too nonspecific.

I don't know if it makes sense to get rid of them, though, because sometime you need a term with which to tag a protein from a publication that affects cytokine release but for which the mechanism has not been elucidated.

I think the new terms I have been suggesting today will cover most things that affect inflammatory cytokine production in an infection.

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@kzudock please remove PATHGO_0000275 & its subclass PATHGO_0000060
