### ISSUE TITLE
Pathogen vacuole formation/maintenance factor

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#50]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Pathogen vacuole formation/maintenance factor

## Synonyms
None

## Textual definition
Many proteins from intracellular bacterial pathogens, particularly Brucella, Chlamydia, Coxiella, Ehrlichia, Listeria, Legionella, Mycobacterium, and Salmonella, manipulate the recruitment and activation of host cytoskeletal proteins, small GTPases, and membrane lipids, to generate intracellular niches in which they can replicate in a protected environment.

## Suggested parent term
PATHGO_0000073 (determinant of pathogenicity)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
Would terms related to this intracellular niche concept fit under "proliferation and survival factor"  PATHGO_0000105?

**Comment by genegodbold** [comment]
It might be too abstract, but I think there needs to be _some_ term that captures not just that a particular host cellular process (membranes, small GTPases, cytoskeleton) is being hijacked, but _what_ it is being hijacked for (a little teleology). Something like "construction/maintenance of pathogen replication vacuole within host cell", though that sounds kinda clumsy.

Researchers call them things like Legionella-containing vacuole (LCV), Salmonella-containing vacuole (SCV), Brucella-containing vacuole (BCV), Coxiella-containing vacuole (CCV), Listeria busts out of its vacuole to get to the cytoplasm where it motors around, Chlamydia-containing vacuoles are  also called _inclusions_, Mycobacteria-containing vacuole (MCV), Ehrlichia-containing vacuoles (ECV). They aren't "made" the same way and they don't look alike and they all have different ways of getting out of them--often on the way to killing the host cell.

**Comment by genegodbold** [comment]
Hey @jproesch, I think those two classes are different, but I'm open to discussion. At the very least, there are *so* many of the latter that they deserve to be distinguished. 

When I hear "survival" I think nutrient acquisition. In contrast, these factors, of which there are hundreds, are involved in manipulating host cell membrane components and cytoskeletal components to manufacture and maintain safe spaces for intracellular replication and keep them isolated (to a degree) from the normal endomembrane dynamics of the cell. Do they "help" in obtaining nutrients? I am sure they do--or at least they make provision for them, but they are distinguished by their effects on altering the endomembrane system.

Some examples:
SidF of Legionella pneumophila is a phosphatidylinositol polyphosphate 3-phosphatase that specifically hydrolyzes the D3 phosphate of PI(3,4)P(2) and PI(3,4,5)P(3). This activity is necessary for anchoring of PI(4)P-binding effectors to bacterial phagosomes [PMID22872863].

AnkX from Legionella pneumophila modifies host Rab small GTPases by phosphocholination [PMID21822290]. Phosphocholination of Rab interferes with host endocytic recycling and is critical for inhibiting fusion of the Legionella-containing vacuole with lysosomes [PMID28944216]. AnkX is an ankyrin-repeat domain-containing translocated effector of the Dot/Icm T4BSS of Legionella pneumophila that is expressed during the post-exponential phase of intracellular growth [PMID26545400].

AptA  localizes to Anaplasma phagocytophilum inclusions during infection and activates MAPK pathways. AptA expression in mammalian cells induces phosphorylation of Erk1/2 through MEK. AptA interacts specifically and directly with host intermediate filament protein vimentin which colocalize in infected host cells. The MAPK pathway is activated through vimentin in infected neutrophils.

Ats-1 induces the formation of autophagosome-like vesicles containing multiple host autophagy proteins  by binding host BECN1, a core component in the PtdIns3K complex that initiates host cell autophagy. The intracellular bacteria appear to use these autophagic inclusions to proliferate [PMID23388398].

ChlaDUB1 and the related ChlaDUB2 are chlamydial effectors that can perform both lysine deubiquitination and lysine acetyltransferase reactions using the same conserved Cys residue and a unique inserted helix (VR3). The His203Tyr mutation inactivates both enzymatic activities. The deubiquitinase activity of these effectors is responsible for the redistribution of the Golgi around the inclusion body in host cells infected with bacteria. The effector localizes to the Golgi during infection [PMID30397340].

Cig57 is important for development of the Coxiella containing vacuole [PMID25080348]. Cig57 binds, via its endocytic sorting motif, to host FCHO2 protein via , to interfere with clathrin-dependent vesciular transport. Clathrin is found around CCV and clathrin recruitment to the CCV is attenuated in the absence of FCHO2 [PMID28002452].



Francisella tularenesis mutants in which the gene for DipA is disabled are targeted, in murine and human macrophages, to autophagic vacuoles unlike wild-type bacteria. DipA is required for cytosolic replication but not phagosomal escape. DipA has four Sel1-like repeats and a coiled-coil motif but otherwise appears novel. DipA is membrane associated and is localized on the bacterial surface during macrophage infection. The coiled-coil domain is indispensable for membrane association.

**Comment by jproesch** [comment]
Hmmmm, ok. Sounds closer to fitting in under the endomembrane system terms. Although this seems to be maybe one of those higher order/downstream effects...i.e. the direct effects for the examples above are on endomembrane dynamics, cytoskeleton, ubiquitination,etc. and the result is formation/maintenance of vacuole (intracellular niche?) that enables intracellular survival/proliferation.

**Comment by jproesch** [comment]
@kzudock Please add "pathogen vacuole formation/maintenance factor" and "mediates pathogen vacuole formation/maintenance" as subclasses to "PathGO_0000105" and"PathGO_0000150" 

A gene product that mediates proliferation and survival by contributing to the formation or maintenance of pathogen vacuole, generating and  intracellular niches in which they can replicate in a protected environment.

A mechanism that mediates proliferation and survival by contributing to the formation or maintenance of pathogen vacuole, generating and  intracellular niches in which they can replicate in a protected environment.

**Comment by jproesch** [comment]
@kzudock disregard previous comment!
