### ISSUE TITLE
Mediates host actin rearrangement

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#57]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Mediates host actin rearrangement

## Synonyms
None

## Textual definition
The parasite rearranges the host cell actin cytoskeleton

## Suggested parent term
PATHGO_0000028 (disrupts cytoskeleton maintenance)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Agree that this was lacking.  New term added.

**Comment by jacakrj1** [comment]
PR #119
