### ISSUE TITLE
Mediates host actin polymerization

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#58]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Mediates host actin polymerization

## Synonyms
None

## Textual definition
The parasite manipulates components of the host cell so as to induce actin polymerization

## Suggested parent term
Mediates host actin rearrangement (newly proposed)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Yes, we had depolymerization, but should have polymerization, too.

**Comment by jacakrj1** [comment]
Addressed in PR #119
