### ISSUE TITLE
Mediates host actin rearrangement allowing parasite invasion of host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#59]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Mediates host actin rearrangement allowing parasite invasion of host cell

## Synonyms
None

## Textual definition
The parasite manipulates host components so as to rearrange the actin cytoskeleton so that it can invade the host cell.

## Suggested parent term
Mediates host actin rearrangement (newly proposed)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jacakrj1** [comment]
Going to leave this one out.  I think the new term 'host actin rearrangement' is sufficient.

**Comment by jacakrj1** [comment]
Addressed in PR #119

**Comment by genegodbold** [comment]
Hey @rjacak, I proposed this because actin rearrangement doesn't always result in parasite invasion but there are a significant number of parasite proteins that *do* specifically trigger/allow invasion. But I recognize that there is a term for host cell invasion so that the intersection of these factors will probably yield the necessary information for a particular sequence.

**Comment by jacakrj1** [comment]
I figured that's what you were getting at there, so I included an editorial comment alongside the definition that provides that additional info.  Sorry, should have mentioned that above.

**Comment by genegodbold** [comment]
Maybe we can keep this one in reserve in case it does prove uniquely necessary to describe some invasion proteins that use actin specifically for invasion?
