### ISSUE TITLE
Induces host apoptosis

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#60]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Induces host apoptosis

## Synonyms
None

## Textual definition
The parasite induces/activates apoptosis, a form of regulated cell death, in a host cell through manipulation of components of the cytosol.

## Suggested parent term
PATHGO_0000169 (regulates apoptosis) 
See issue #90 

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
will be resolved with Issue #90
