### ISSUE TITLE
Guanine exchange factor for host small GTPase

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#63]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Guanine exchange factor for host small GTPase

## Synonyms
None

## Textual definition
A parasite protein that acts as a guanine exchange factor (GEF) for a host small, monomeric, GTPase (Ras, Rho, Rab, etc.) inducing the expulsion of a bound GDP for a fresh GTP and thereby activating the protein.

## Suggested parent term
PATHGO_0000015 (cellular signaling disruption factor)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold Is PATHGO_0000181 GTPase activating protein a more appropriate parent class?

**Comment by genegodbold** [comment]
I don't think so--those are two separate activities. Small GTPases act as molecular switches: "on" = bound GTP and "off" = bound GDP. The small GTPase as intrinsic GTPase activity so that the GTP will eventually be hydrolyzed to GDP, so it has a built-in inactivating feature--but this takes awhile. So the cell has things that can speed this up: GTPase activating proteins (GAPs) that grab the small GTPase bound to GTP and make it hydrolyze the GTP to GDP immediately. And there are guanine exchange factors (GEFs) that kick out the GDP (normally it is slow to leave). Since the energy balance of the cell is such that there is generally an abundance of GTP over GDP, this means that GEF activity amounts to a way to activate the small GTPase (since GTP will diffuse in and the process continues). But GEFs and GAPs are opposing proteins. There are also GDP-dissociation inhibitors (GDI) which lock the small GTPase down with GDP. 

I have seen examples of both parasite GAPs and GEFs but not GDIs (yet)
