### ISSUE TITLE
Determinant of type VII secretion

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#67]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Determinant of type VII secretion

## Synonyms
None

## Textual definition
Component of a type VII secretion system that can mediate the entry of bacterial effectors into the host cell.

[Type VII secretion systems of Mycobacterium tuberculosis are used to get secreted effectors into the host where they do wicked things.]

## Suggested parent term
PATHGO_0000102 (determinant of protein effector secretion)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@kzudock please add "Determinant of type VII secretion" as a subclass to PATHGO_0000102 (determinant of protein effector secretion) and "mediates type VII secretion" as a sublcass to PATHGO_0000110 mediates secretion of protein effectors
