### ISSUE TITLE
Host elongation factor-1 inactivator

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#68]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Host elongation factor-1 inactivator

## Synonyms
None

## Textual definition
Parasite protein that inactivates host ribosomal elongation factor 1, leading to the inhibition of protein synthesis in the host cell.

[There are three glucosylating toxins from Legionella pneumophila that fall into this category.]

## Suggested parent term
PATHGO_0000034 (protein synthesis inhibition factor)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by aernlund** [comment]
This is now term PATHGO:0000244
