### ISSUE TITLE
Host eukaryotic initiation factor repressor

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#70]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Host eukaryotic initiation factor repressor

## Synonyms
None

## Textual definition
Parasite protein that represses host protein translation by modifying a host eukaryotic initiation factor

## Suggested parent term
Eukaroytic initiation factor modulator (newly proposed)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by aernlund** [comment]
Added mediates initiation factor repression under parent "mediates protein synthesis inhibition".
