### ISSUE TITLE
Mediates elongation factor 1 inactivation

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#72]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
(e.g., Asplenia)

## Synonyms
(e.g., Absent spleen)

## Textual definition
Inactivation of elongation factor 1 with the effect of repressing protein translation in the host cell.

[The three legionella glucosylating toxins fall into this category as well as SidI from Legionella and N protein from SARS-CoV]

## Suggested parent term
PATHGO_0000006 (mediates protein synthesis inhibition)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by aernlund** [comment]
This is now term PATHGO:0000244

**Comment by genegodbold** [comment]
Yippee!
(Or is that not professional :-)
