### ISSUE TITLE
Factor countering host immunoglobulin

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#75]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Factor countering host immunoglobulin

## Synonyms
None

## Textual definition
These parasite factors either sequester host cytokines by binding to them like poxviral cytokine binding proteins/receptors do or they proteolytically destroy host immunoglobulins.

[Examples of bacterial proteases: IgA1P, IdeS, EndoS, ZmpC from Streptococcus; InvD from Yersinia pseudotuberculosis; and BatB from Bordetella]

## Suggested parent term
PATHGO_0000090 (immune evasion and subversion factor)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold Propose breaking into two terms, one for proteolytic cleavage "host immunoglobulin neutralization factor" and another to cover cytokine sequestration as this is an indirect effect on immunoglobulins.  Reasonable?

**Comment by genegodbold** [comment]
Yes, I think that is good.
I think we should only focus on the direct effects. (I mean, inhibiting the ligation of TLR4 receptors or TNFR has SO many effects, but you can only mention the primary.) 

Proteases can cut our other proteins can bind immunoglobulins to neutralize them.

Similarly, proteases can cut chemokines or other cytokines (IL-8, say) or viral (faux) chemokine receptors can sequester them. Effect is the same so you can maybe distinguish how it happens in the children, but the primary effect is the same.

I hope this makes sense.

**Comment by genegodbold** [comment]
Let me give some examples of interference with cytokines and immunoglobulins.

(1) Variola B17R is a receptor for host interferon-alpha and IFN-beta. VARV B17 protein blocks the antiviral activity of several human type I IFNs. Purified B17R binds to the majority of human type I interferons [PMID20019241]. B17 binds to the host cell surface via glycosaminoglycans to effectively block antiviral interferon-alpha activities in solution. This interaction is similar to that of B18R from vaccinia virus and B16R from monkeypox virus [PMID21372110].
(2) Vaccinia Interleukin-18 binding protein binds host IL-18 and inhibits IL-18 induced IFNgamma production [PMID16281988]. In a murine intranasal model of infection, C12L deletion mutants were attenuated for virulence [PMID12388820]. 
(3) Plasmodium falciparum DBLMSP1 and DBLMSP2 bind human immunoglobulin M (IgM). They can form multimers through their C-terminal domains that increase the avidity of this interaction. This activity might mask these proteins from the host immune system [PMID27226583].
(4) Alp1 of Aspergillus fumigatus allows control of host complement activation by cleaving host components C3, C4, C5 and C1q as well as immunoglobulin G (IgG). Alp1 is the primary molecule responsible for this cleavage and is present in large amounts in culture supernatant [PMID20498262].
(5) BatB binds host immunoglobulin in vitro. In vivo, a B. pertussis mutant in which the gene for BatB is deleted was cleared more rapidly from the lower respiratory tract because of its inability to overcome the immune defenses. BatB prevents nonspecific antibodies from facilitating neutrophil-mediated clearance [PMID18426869].
(6) Streptococcal EndoS removes carbohydrates from native immunoglobulin G (IgG). This renders antibodies incapable of eliciting host effector functions through either complement or Fcgamma receptors, providing the bacteria with a survival advantage [PMID24753590].
(7) IgA1 proteases are extracellular proteaes that cut the hinge region of human immunoglobulin A1 (IgA1) which predominate on mucosal membranes. Those from H. influenzae are serine protease autotransporters whose proteolytic activity is limited to the hinge region of IgA1 [PMID18165266].
(8) LasB is a T2SS effector of Pseudomonas aeruginosa secreted into the extracellular milieu [PMID24626230]. LasB is the most abundant protein in the secretome of at least one strain of P. aeruginosa [PMID28790180]. Pseudolysin/LasB can specifically degrade the host inflammatory cytokine IL-6 [PMID16913841].
(9) Streptococcal SpyCEP has secreted and cell-associated forms. It cuts and inactivates the human chemokine IL-8 and other human CXC chemokines that contain the ELR motif [PMID26866214]. In a mouse model of disease, it inhibits clearance of the bacteria from muscle and enhances bacterial spread. When expressed in Lactococcus lactis, it renders the bacterium pathogenic in mice [PMID20158613].
