### ISSUE TITLE
Splitting PATHGO_0000210 (invasion and dissemination factor) into two with name change to clarify

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#77]
There are hundreds of invasion factors--they are necessary to most parasites--but not so many dissemination factors. The latter often, but not always, requires some damage to host tissues. Because there is no "natural" link between these two things, it would be better to have one term for "invasion factor" and another for "dissemination factor".  I think it would be best to let "invasion factor" keep the PATHGO_0000210 designation and the name should be changed to "factor mediating host cell invasion"

_New Definition_ for "Factor mediating host cell invasion"
These factors mediate the invasion of a host cell by a parasite or a toxin subunit, following a cellular binding event. These factors get the parasite or the toxin from a position stationed at the cell membrane to inside the host cell.

Suggested Parental Term
The parent term should remain PATHGO_0000073 (determinant of pathogenicity)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
PATHGO_0000196 (determinant of extracellular matrix destruction) is a subclass to PATHGO_0000210, but does not fit with updated term name.  Need to find an appropriate parent class
