### ISSUE TITLE
Factor mediating host barrier traversal

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#79]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Factor mediating host barrier traversal

## Synonyms
None

## Textual definition
Protein that mediates the traversal of a host barrier, either external (separating the environment from the host) or internally (separating different host areas) for a parasite. The traversal could result in host damage but does not necessarily do so. All factors in this category will necessarily mediate the _dissemination_ of the parasite since they make the other side of the barrier is now available for colonization. Some, but by no means all, of these factors will be able to mediate PATHGO_0000162 (epithelial layer disruption).

## Suggested parent term
This should be a child under "dissemination factor" a term that I have proposed be split from "invasion and dissemination factor"

[Examples Macrophage infectivity potentiator from Legionella; Exylysin from Pseudomonas; Pseudomonas exotoxin S; Pseudomonas exotoxin T; Shigella extracellular protease]

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
Linked to Issue 77

**Comment by genegodbold** [comment]
Excellent; this is much less abstract than invasion; very well played, indeed.
