### ISSUE TITLE
Modulates autophagy or xenophagy in host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#83]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Modulates autophagy or xenophagy in host cell

## Synonyms
None

## Textual definition
Alteration of host autophagy or xenophagy for the benefit of the parasite.

## Suggested parent term
This term could be a child under the newly proposed parent term "Modulation of host process by parasite"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold there is some overlap here with "inhibits phagocytosis"  (PATHGO_0000232) regarding xenophagy.  Xenophagy could be included as a synonym for the phagocytosis terms.  Is there a need for "modulates" to allow a non-inhibitory effect?  Also, regarding autophagy, do you have an example for this that is distinct from xenophagy?

**Comment by genegodbold** [comment]
Hey @jproesch, 
Xenophagy/autophagy and phagocytosis are two different things, though they can flow together. Eukaryotic cells have specific processes that bacteria (for example) can interact with independent of phagocytic processes. Some examples:

Anaplasma translocated substrate-1: Ats-1, a T4SS effector, binds host beclin 1 (UniProtQ14457), a subunit of the class III PI3K and Atg14L which helps induce autophagy. Ats-1 localizes the host proteins beclin-1, Atg14L, and LC3 on the Anaplasma inclusion. This induces the membrane vesicle formation. Ats-1 by itself can nucleate autophagosomes decorated around Anaplasma inclusions with ER autophagy proteins. Ats-1 promotes the growth of Anaplasma phagocytophilum in host cells. Depleting beclin suppresses parasite infection [PMID23197835]-  [PMID23388398].

Deficient in intracellular replication A: F. tularensis mutants in which the gene for DipA is disabled are targeted, in murine and human macrophages, to autophagic vacuoles unlike wild-type bacteria. DipA is required for cytosolic replication but not phagosomal escape. Macrophage vacuoles containing replication-deficient bacteria were labeled with ubiquitin and the autophagy receptors SQSTM1/p62 and NBR1, and their formation was decreased in macrophages from either ATG5-, LC3B- or SQSTM1-deficient mice, indicating recognition by the ubiquitin-SQSTM1-LC3 pathway [PMID22863802].

BopA is an effector injected into host cells via a type III secretion system. It prevents targeting of the B. pseudomallei bacterium via LC3-associated phagocytosis, a form of xenophagy [PMID22790007].

Escherichia coli secreted protein G (EspG): Both EspG and EspG2 function as GTPase activating proteins for Rab1 to inhibit autophagy and vesicular traffic from the ER to the Golgi [PMID22425230]. 

CbpC of Streptococcus pneumoniae dampens autophagy by promoting the degradation of host ATG14 (UniprotQ6ZNE5) through its interaction with sequestosome1 [PMID32508214].

CvpB/Cig2 is a T4SS effector important for interactions between the Coxiella-containing vacuole and host autophagosomes and this enhances the fusogenic properties of the CCV. The CCV has a unique ability to fuse promiscuously with other host compartments of the C. burnetii-infected cell. This requires a functional host autophagic system [PMID25080348].

Etf-1 is a T4aSS effector that localizes to ehrlichial inclusions and binds Rab5 and the autophagy-initiating class III PtdIns-3-kinase complex. Ectopically expressed Etf-1 activates class III PtdIns-3 kinase and induces autophagosome formation. It also enhances proliferation of Ehrlichia. The bacteria manipulates host autophagy for its own nutritional needs [PMID27541856]. 

I've got a couple dozen more for bacteria and maybe 10 for viruses, but that's a taste.

**Comment by genegodbold** [comment]
Also @jproesch, I might be thinking of phagocytosis differently than most people (I don't know). When the people I'm reading investigate phagocytosis, they are concerned with *uptake* of foreign material. So interfering with uptake by influencing the molecular dynamics of the cytoskeleton or the membrane, or phagocytic receptors is sufficient to qualify as interrupting phagocytosis.

So notice that what happens to the cellular material AFTER that, doesn't enter into the disruption of phagocytosis. Of course, PathGO makes this same distinction--you  have a bunch of terms that deal with what happens to the material AFTER it gets in the cell. Does it get interrupted on the way to the phagosome? The lysosome? So you see that you have a distinction based on "uptake" and "delivery" already in the ontology. Xenophagy/autophagy use the same set of host proteins (beclin, autophagy receptors, some vesicle markers) but involve an alternate pathway for the final disposal of the material that has been taken up. I think it is important to note when these host pathways are inhibited/defeated by the parasite.

**Comment by jproesch** [comment]
@genegodbold thanks!  I was seeing things out there where some folks were using phagocytosis and xenophagy synonymously, but I am also seeing the nuance I think you are pointing out...that phagocytosis is uptake into the cell, while xenophagy/autophagy happens after.  Given we have some related terms concerning what happens after under endomembrane system, I'm thinking this might also fit there.

**Comment by genegodbold** [comment]
@jproesch 
Yes, my only point is that we need a term that recognizes that *these* specific host processes are being manipulated by the parasite. None of the others are synonymous.
