### ISSUE TITLE
Modulation of host process by parasite

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#84]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Modulation of host process by parasite

## Synonyms
None

## Textual definition
This is a broad term which should have many children including:
Modulates autophagy or xenophagy in host cell
Modulates small GTPase dynamics in host cell
Modulates transcription in host cell
Modulates translation in host cell
Modulates cell cycle in host cell
Modulates ubiquitin dynamics in host cell
Modulates apoptosis in host cell
Modulates cytoskeleton in host cell
Modulates membrane dynamics in host cell

## Suggested parent term
I think this term should go under PATHGO_0000114 (mechanism of pathogenicity)

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
not needed as a top level term;  all above terms can either be top level or fit under other existing top level terms
