### ISSUE TITLE
Modulates small GTPase dynamics in host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#85]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Modulates small GTPase dynamics in host cell

## Synonyms
None

## Textual definition
Alteration of host small GTPase dynamics for the benefit of the parasite. This manipulation can occur through direct binding of host small GTPases or by alteration of the activity or abundance of the proximal effectors of small GTPases, including GTPase activating proteins (GAPs), guanine exchange factors (GEFs), or guanine dissociation inhibitors (GDIs).

## Suggested parent term
The parent term should be the newly proposed "Modulation of host process by parasite"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@kzudock please add this term and the corresponding determinant term as subclasses to PATHGO_0000165 and PATHGO_0000015 respectively
