### ISSUE TITLE
Modulates transcription in host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#86]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Modulates transcription in host cell

## Synonyms
None

## Textual definition
Parasite alteration of transcription in host cell. 

## Suggested parent term
The parent term should be the newly proposed "Modulation of host process by parasite"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
Add "modulates transcription in host cell" and "host cell transcription modulation factor" as subclasses to PATHGO_0000164 and PATHGO_0000179 respectively to resolve this issue
