### ISSUE TITLE
Modulates translation in host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#87]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Modulates translation in host cell

## Synonyms
None

## Textual definition
Alteration of host translation for the benefit of the parasite.

## Suggested parent term
This term could be a child under the newly proposed parent term "Modulation of host process by parasite"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@aernlund  please add "modulates host cell translation" as synonym for PATHGO_0000006 and "host cell translation modulator" as synonym for PATHGO_0000034 to resolve this issue.

**Comment by aernlund** [comment]
Done!
