### ISSUE TITLE
Modulates cell cycle in host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#88]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Modulates cell cycle in host cell

## Synonyms
None

## Textual definition
Alteration of the cell cycle in a host cell for the benefit of the parasite.

## Suggested parent term
This term could be a child under the newly proposed parent term "Modulation of host process by parasite"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
Modify PATHGO_0000004 and PATHGO_0000063 to "host cell cell cycle modulator" "modulates cell cycle in host cell"; modify definitions accordingly
