### ISSUE TITLE
Modulates ubiquitin dynamics in host cell

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#89]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Modulates ubiquitin dynamics in host cell

## Synonyms
None

## Textual definition
Alteration of host ubiquitin dynamics for the benefit of the parasite. The parasite activity modulates or redirects a host E3 ubiquitin ligase, or has E3 ubiquitin ligase activity, or alters host E2 enzymes, or removes ubiquitin from a target protein.

[There are more than 60 sequences that fall under this term in bacteria and viruses.]

## Suggested parent term
This term could be a child under the newly proposed parent term "Modulation of host process by parasite"

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
Add "modulates ubiquitin dynamics in host cell" and "host cell ubiquitin dynamics modulator" as subclasses to PATHGO_0000164 and PATHGO_0000179 respectively to resolve this issue
