### ISSUE TITLE
Modulates apoptosis in host cell; should replace PATHGO_0000169 (regulates apoptosis)

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#90]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Modulates apoptosis in host cell

## Synonyms
None

## Textual definition
Alteration of host apoptosis for the benefit of the parasite. 

[This may also be broadened later to include other forms of regulated cell death.]

## Suggested parent term
This term could be a child under the newly proposed parent term "Modulation of host process by parasite" Note that I am advocating that this term should replace PATHGO_0000169 (regulates apoptosis). I would advocate for keeping the number but changing the name "regulates apoptosis" to "modulates apoptosis in host cell" with two children
1) PATHGO_0000178 (suppression of apoptosis) should be changed to "suppression of apoptosis in host cell"
2) newly proposed term "induction of apoptosis in host cell" 

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
Change label of PATHGO_0000169 to "modulates apoptosis in host cell" and label of PATHGO_0000192 to "host cell apoptosis modulator" (change definitions accordingly)

Change PATHGO_0000178 to "suppresses apoptosis in host cell" and add appropriate definition.

Add term "induces apoptosis in host cell" as subclass to PATHGO_0000169 

Add terms "host cell apoptosis suppressor" and "host cell apoptosis inducer" as subclasses to PATHGO_0000192
