### ISSUE TITLE
Modulates cytoskeleton in host cell; should replace PATHGO_0000028 (disrupts cytoskeleton maintenance)

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#91]
I think this term makes more sense than PATHGO_0000028 (disrupts cytoskeleton maintenance) which is the child under parent term PATHGO_0000166 (disrupts cellular structure). Not all parasite manipulations amount to a disruption, though they certainly can do so.

For new term requests, please provide the following information:
## Preferred term label
Modulates cytoskeleton in host cell

## Synonyms
None

## Textual definition
Alteration of the cytoskeleton, including intermediate filaments, actin fibers, or microtubules, in a host cell for the benefit of the parasite.

## Suggested parent term
This term could be a child under the newly proposed parent term "Modulation of host process by parasite"

Under this term should be the following children:
(1) Mediates microtubule rearrangement
(1a) Mediates microtubule rearrangement allowing parasite invasion of host cell
(2) Mediates actin rearragement
(2a) PATHGO_0000216 (mediates actin depolymerization)
(2b) Mediates actin polymerization
(2c) Mediates actin rearrangement allowing parasite invasion of host cell

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@aernlund please 

1) change label of PATHGO_0000028 "disrupts cytoskeleton maintenance" to "modulates cytoskeleton in host cell" and change definition accordingly.  Note that all child term definitions will also need to be changed to match new parent label
2) change label of PATHGO_0000183 "cytoskeleton disruption factor" to "host cell cytoskeleton modulator" and change definition accordingly (also for all child terms)
3) add determinant terms for "host actin rearrangement factor" and "host actin polymerization factor" to match PATHGO_0000260 and PATHGO_0000261

**Comment by aernlund** [comment]
Done!
