### ISSUE TITLE
Factor that disrupts focal adhesions of host cells

### ISSUE THREAD

**Issue by genegodbold** [jhuapl-bio/pathogenesis-gene-ontology#95]
Please enter your suggested changes or comments here.  If your comment relates to a specific term, please provide the PathGO id or rdfs:label of the term in addition to your comment.

For new term requests, please provide the following information:
## Preferred term label
Factor that disrupts focal adhesions of host cells

## Synonyms
None

## Textual definition
These are many bacterial proteins of enteric pathogens that disrupt the focal adhesions of host cells in the course of pathogenesis.

## Suggested parent term
The parent of this child should be either PATHGO_0000183 (cytoskeleton disruption factor) **or** PATHGO_0000182 (cellular structure disruption factor). I think I favor the latter.

## Attribution
https://orcid.org/0000-0002-5702-4690

**Comment by jproesch** [comment]
@genegodbold test comment

**Comment by genegodbold** [comment]
@jproesch We'll see if the mention gets to my inbox, eventually.
